/* ChronoNebula Universe — world data
   Source: ChronoNebula Universe World Bible by Zan Ye Htet (ZXXNGOD)
   Clan palettes follow the official Codex palette cards; hex values are
   calibrated from the card artwork. */

export const BRAND = {
  name: 'ChronoNebula',
  sub: 'AI × Fashion',
  year: '8888 AD',
  creator: 'ZXXNGOD',
  creatorName: 'Zan Ye Htet',
  palette: {
    deepVoid: '#050505',
    lunarWhite: '#F5F5F5',
    nebulaEmerald: '#00FFB3',
    chromeSilver: '#C7C7C7',
    astralGray: '#1A1A1A',
    cosmicBlue: '#0D1B2A',
    novaGold: '#D4AF37',
  },
};

export const PLANETS = [
  {
    id: 'jenova',
    name: 'Jenova',
    tone: 'Luminous ice-white world of twin civilizations',
    color: '#cfe4ff',
    glow: '#8fc8ff',
    radius: 1.15,
    orbit: 2.5,
    speed: 0.16,
    clans: ['white-nova', 'rogue-lunaris'],
  },
  {
    id: 'chrono',
    name: 'Chrono',
    tone: 'Heart of Chrono Energy, ringed by time itself',
    color: '#9fe8c9',
    glow: '#00ffb3',
    radius: 1.35,
    orbit: 3.4,
    speed: 0.13,
    ringed: true,
    clans: ['lumina'],
  },
  {
    id: 'earth',
    name: 'Earth',
    tone: 'Old cradle, three cultures under one neon sky',
    color: '#7fb8d8',
    glow: '#59c4e8',
    radius: 1.2,
    orbit: 4.3,
    speed: 0.11,
    clans: ['solar-punk', 'cyberpunk', 'chrono-punk'],
  },
  {
    id: 'vaelora',
    name: 'Vaelora',
    tone: 'An ocean that remembers everything it touches',
    color: '#3f97b8',
    glow: '#4fc8e8',
    radius: 1.1,
    orbit: 5.2,
    speed: 0.095,
    clans: ['ocean-void'],
  },
  {
    id: 'achronox',
    name: 'Achronox',
    tone: 'Dark seat of the Monolith and its guardians',
    color: '#3d3550',
    glow: '#6f5fae',
    radius: 1.3,
    orbit: 6.1,
    speed: 0.082,
    clans: ['black-chronoa', 'black-order'],
  },
  {
    id: 'milorus',
    name: 'Milorus',
    tone: 'Volcanic forge-world of dragon engineers',
    color: '#b85c33',
    glow: '#e8842b',
    radius: 1.05,
    orbit: 7.0,
    speed: 0.072,
    clans: ['dragon-cypher'],
  },
  {
    id: 'mars',
    name: 'Mars',
    tone: 'Terraformed frontier of the pioneer councils',
    color: '#a35a3d',
    glow: '#c86a3c',
    radius: 0.95,
    orbit: 7.9,
    speed: 0.064,
    clans: ['martian-clan'],
  },
  {
    id: 'gaia-prime',
    name: 'Gaia Prime',
    tone: 'A world where the cities themselves are alive',
    color: '#7da84e',
    glow: '#a4e83c',
    radius: 1.12,
    orbit: 8.8,
    speed: 0.057,
    clans: ['bio-punk'],
  },
];

export const CLANS = [
  {
    id: 'black-chronoa',
    name: 'Black Chronoa',
    planet: 'Achronox',
    capital: 'Cindra',
    leader: 'Queen Ani Thu Zard',
    essence: 'Memory · Discipline',
    summary:
      'The main central clan and guardians of the First Monolith created by ZXXNGOD. Their culture is built around monumental architecture, ritual, and the preservation of history.',
    motto: 'Memory shapes destiny. We endure, so that others may become.',
    palette: [
      { name: 'Void Black', hex: '#0B0B0D' },
      { name: 'Obsidian Shard', hex: '#3A3D42' },
      { name: 'Temporal Violet', hex: '#4B3E8E' },
      { name: 'Chrono Gold', hex: '#8A7A45' },
      { name: 'Paradox Teal', hex: '#1F5C55' },
    ],
    accents: ['#6E7178', '#2E3D55', '#E8EFF2'],
    featured: true,
  },
  {
    id: 'white-nova',
    name: 'White Nova',
    planet: 'Jenova',
    capital: 'Nova Nexus',
    leader: 'NEXUS, Planetary AI',
    essence: 'Technology · AI · Logic',
    summary:
      'The most advanced civilization of the universe, designing the future through architecture, science, and fashion. They believe intelligence is the greatest light.',
    motto: 'From knowledge comes light. From light comes tomorrow.',
    palette: [
      { name: 'Absolute White', hex: '#F6F8FA' },
      { name: 'Titanium Alloy', hex: '#AEB6BD' },
      { name: 'Nova Core', hex: '#00E5FF' },
      { name: 'Data Violet', hex: '#5B3FA8' },
      { name: 'Void Black', hex: '#0B0D10' },
    ],
    accents: ['#C4C9CE', '#7FD8FF', '#E832B8'],
    featured: true,
  },
  {
    id: 'rogue-lunaris',
    name: 'Rogue Lunaris',
    planet: 'Jenova',
    capital: 'Moonlight Luna',
    leader: 'High Moon Oracle',
    essence: 'Moonlight · Ancient Wisdom',
    summary:
      'A celestial civilization preserving lunar traditions, rituals, and emotional resonance. They seek truth beyond logic, guided by the moon and the whispers of ancient time.',
    motto: 'We do not fear the dark. We listen to its wisdom.',
    palette: [
      { name: 'Rouge Crimson', hex: '#8E1420' },
      { name: 'Lunaris Pearl', hex: '#E9E6E4' },
      { name: 'Eclipse Black', hex: '#0C0F16' },
      { name: 'Shadow Violet', hex: '#4A4066' },
      { name: 'Lunar Gold', hex: '#A89663' },
    ],
    accents: ['#D8323C', '#7C8087', '#DCE0EA'],
  },
  {
    id: 'lumina',
    name: 'Lumina',
    planet: 'Chrono',
    capital: 'Zemo',
    leader: 'High Luminary',
    essence: 'Time · Balance',
    summary:
      'Keepers of balance and stewards of Chrono Energy, the origin of light in the universe. Through harmony they guide civilizations and protect the sacred flow of time.',
    motto: 'We do not seek power. We preserve balance.',
    palette: [
      { name: 'Celestial White', hex: '#F4F4F6' },
      { name: 'Zemo Pearl', hex: '#E6E4EC' },
      { name: 'Astral Gold', hex: '#C8A64B' },
      { name: 'Nebula Violet', hex: '#4B3C8C' },
      { name: 'Lumina Blue', hex: '#35BFEF' },
    ],
    accents: ['#C9CDD4', '#E8D477', '#58A8E0'],
  },
  {
    id: 'solar-punk',
    name: 'Solar Punk',
    planet: 'Earth',
    capital: 'Neon Metro',
    leader: 'The Council',
    essence: 'Nature · Sustainability',
    summary:
      'Builders of eco-cities powered by renewable technology, where gardens climb the towers and sunlight is currency.',
    palette: [
      { name: 'Solar Gold', hex: '#E8B84B' },
      { name: 'Neon Leaf Green', hex: '#8FD435' },
      { name: 'Sky Azure', hex: '#59C4E8' },
      { name: 'Terracotta Clay', hex: '#B96B44' },
      { name: 'Void Black', hex: '#17181A' },
    ],
    accents: ['#E8A83C', '#3E8FA8', '#E8A8B0'],
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    planet: 'Earth',
    capital: 'Neon Abyss',
    leader: 'Independent Networks',
    essence: 'Digital Freedom',
    summary:
      'A neon metropolis of cybernetics, hackers, and futuristic culture, where identity is written and rewritten in light.',
    palette: [
      { name: 'Neon Cyber-Blue', hex: '#2FD4FF' },
      { name: 'Glitch Magenta', hex: '#E832B8' },
      { name: 'Carbon Fiber Black', hex: '#17181C' },
      { name: 'Acidic Neon-Green', hex: '#8FE83C' },
      { name: 'Chrome Steel', hex: '#B8C8D4' },
    ],
    accents: ['#9B7FE8', '#E8A32C', '#F04358'],
  },
  {
    id: 'chrono-punk',
    name: 'Chrono Punk',
    planet: 'Earth',
    capital: 'Yangon',
    leader: 'Nomadic Leaders',
    essence: 'Time Exploration',
    summary:
      'Temporal explorers who travel unstable timelines, salvaging what the centuries leave behind and wearing it as armor.',
    palette: [
      { name: 'Obsidian Black', hex: '#131316' },
      { name: 'Temporal Violet', hex: '#5B4A9B' },
      { name: 'Glitch Green', hex: '#3CE84B' },
      { name: 'Rusting Metal', hex: '#A8927C' },
      { name: 'Data Gold', hex: '#9B833C' },
    ],
    accents: ['#3C5A9B', '#F0439B', '#ECEFF2'],
  },
  {
    id: 'ocean-void',
    name: 'Ocean Void',
    planet: 'Vaelora',
    capital: 'Lymnora',
    leader: 'Tide Council',
    essence: 'Ocean · Memory',
    summary:
      'A peaceful ocean civilization preserving memories through living seas, where every current carries a recollection.',
    palette: [
      { name: 'Abyssal Black', hex: '#16181C' },
      { name: 'Lymnora Cyan', hex: '#4FC8E8' },
      { name: 'Deep Trench Violet', hex: '#4B3C8C' },
      { name: 'Coral Pearl', hex: '#ECE8E4' },
      { name: 'Volcanic Teal', hex: '#3C6B64' },
    ],
    accents: ['#3C7FB8', '#E8329B', '#EDEFF0'],
  },
  {
    id: 'black-order',
    name: 'Black Order',
    planet: 'Achronox',
    capital: 'The Cathedral',
    leader: 'Grand Commander',
    essence: 'Order · Authority',
    summary:
      'A military civilization protecting Achronox with absolute discipline. Where the Chronoa remember, the Order enforces.',
    palette: [
      { name: 'Obsidian Black', hex: '#101014' },
      { name: 'Void Steel', hex: '#8B9298' },
      { name: 'Midnight Blue', hex: '#10182B' },
      { name: 'Abyssal Violet', hex: '#4A4270' },
      { name: 'Iron Rust', hex: '#8B6F52' },
    ],
    accents: ['#9B2333', '#7C8087', '#EEEDE8'],
  },
  {
    id: 'dragon-cypher',
    name: 'Dragon Cypher',
    planet: 'Milorus',
    capital: 'Benoth',
    leader: 'Forge Council',
    essence: 'Fire · Honor',
    summary:
      'Masters of volcanic engineering, craftsmanship, and dragon-inspired culture. Their looms are forges; their silk is alloy.',
    palette: [
      { name: 'Obsidian Black', hex: '#16181C' },
      { name: 'Volcanic Red', hex: '#C82B23' },
      { name: 'Geothermal Orange', hex: '#E8842B' },
      { name: 'Ancient Bronze', hex: '#A87C5B' },
      { name: 'Cinder Grey', hex: '#4A4D50' },
    ],
    accents: ['#4B7C4F', '#E8C22B', '#4FA8E0'],
  },
  {
    id: 'martian-clan',
    name: 'Martian Clan',
    planet: 'Mars',
    capital: 'Zylo & Sperastar Haven',
    leader: 'Council of Horizons',
    essence: 'Exploration',
    summary:
      'Terraformers and pioneers expanding civilization beyond Earth, dressed in the colors of canyon dust and sunset.',
    palette: [
      { name: 'Martian Rust', hex: '#9B5B3C' },
      { name: 'Valles Red', hex: '#C82B23' },
      { name: 'Zylo Dust', hex: '#C4ABA0' },
      { name: 'Sperastar Gold', hex: '#A8923C' },
      { name: 'Void Black', hex: '#131316' },
    ],
    accents: ['#3C8FA8', '#4B8B5B', '#E8C22B'],
  },
  {
    id: 'bio-punk',
    name: 'Bio Punk',
    planet: 'Gaia Prime',
    capital: 'Verdantia Arcology',
    leader: 'Circle of Growth',
    essence: 'Living Technology',
    summary:
      'A civilization where architecture, fashion, and technology are living organisms, grown rather than built.',
    palette: [
      { name: 'Verdantia Green', hex: '#8B9B23' },
      { name: 'Fungal Bloom', hex: '#E83C9B' },
      { name: 'Acidic Blue', hex: '#3CC8E8' },
      { name: 'Synthetic Flesh', hex: '#E8C4B8' },
      { name: 'Void Black', hex: '#17181A' },
    ],
    accents: ['#E8E23C', '#E8842B', '#5B3C8C'],
  },
  {
    id: 'apex',
    name: 'Apex',
    planet: 'Unknown',
    capital: 'Future',
    leader: 'Unknown',
    essence: 'Evolution',
    summary:
      'A future elite civilization representing the peak of human potential. Their world has not yet been found. Their palette has not yet been woven.',
    palette: null,
    unknown: true,
  },
];

export const clanById = (id) => CLANS.find((c) => c.id === id);
